Repository CyberCraftInc/cyber-dashboard, pull requests merged in 2019-01, with the labels that each got.

#20 Rspec functional testing for User model
  app/models/project.rb
  app/models/user.rb
  spec/factories/projects.rb
  spec/factories/users.rb
  spec/models/project_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/support/google_auth_stub.rb
Labels: Test

#32 UI tests Google signup and search feature tests and some fix
  app/controllers/omniauth_callbacks_controller.rb
  app/javascript/components/UsersList.vue
  app/views/devise/omniauth_callbacks/new.html.haml
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.haml
  app/views/devise/shared/_links.html.erb
  spec/features/search_users_spec.rb
  spec/features/select_project_spec.rb
  spec/features/sign_in_spec.rb
  spec/features/sign_up_spec.rb
  spec/features/socialmedia_login_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/support/google_auth_stub.rb
Labels: Test, enhancement

#36 Vue component edit user page and dropdown list
  app/controllers/users_controller.rb
  app/javascript/components/header/HeaderDropdown.vue
  app/javascript/components/users/UsersList.vue
  app/javascript/components/users/edit/EditInput.vue
  app/javascript/components/users/edit/EditSubmit.vue
  app/javascript/components/users/edit/UserEdit.vue
  app/javascript/packs/application.js
  app/javascript/src/styles/abstracts/_variables.scss
  app/javascript/src/styles/application.scss
  app/javascript/src/styles/layout/_header.scss
  app/javascript/src/styles/pages/_edit.scss
  app/javascript/src/styles/pages/_home.scss
  app/views/devise/registrations/edit.html.erb
  app/views/layouts/application.html.haml
  app/views/users/edit.html.haml
  app/views/users/index.html.haml
  app/views/users/show.html.haml
  config/routes.rb
  spec/factories/users.rb
  spec/features/edit_user_spec.rb
  spec/features/header_dropdown_spec.rb
Labels: Test, enhancement

#43 Changed user_edit_path to edit_user_path
  config/routes.rb
  spec/features/edit_user_spec.rb
Labels: Fixed

#44 Requests and Routing tests
  spec/controllers/users_controller_spec.rb
  spec/routing/users_routing_spec.rb
Labels: Test

#51 make canEditParameter parameter with policy
  app/controllers/users_controller.rb
  app/views/users/show.html.haml
Labels: Ready to Review

#54 pretty 404 page
  public/404.html
Labels: Ready to Review

#52 add phone validate and fix tests
  app/models/user.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/users.rb
  spec/features/edit_user_spec.rb
  spec/features/search_users_spec.rb
  spec/features/sign_up_spec.rb
  spec/features/socialmedia_login_spec.rb
  spec/phone_helper.rb
  spec/rails_helper.rb
Labels: Ready to Review

#53 make custom label on admin page
  .rubocop.yml
  config/initializers/rails_admin.rb
Labels: Ready to Review

#47 Event targets pop-up window
  app/controllers/events_controller.rb
  app/controllers/users_controller.rb
  app/javascript/components/users/UserEvents.vue
  app/javascript/components/users/UserInfo.vue
  app/javascript/components/users/show/CreateEventButton.vue
  app/javascript/components/users/show/CreateEventPopUp.vue
  app/javascript/src/styles/application.scss
  app/javascript/src/styles/pages/_show.scss
  app/models/event.rb
  app/policies/event_policy.rb
  app/views/users/show.html.haml
  config/routes.rb
Labels: Ready to Review, enhancement
