Repository CyberCraftInc/cyber-dashboard, pull requests merged in 2019-02, with the labels that each got.

#56 add default role
  app/models/user.rb
  db/migrate/20190131134515_add_default_role.rb
  db/schema.rb
Labels: Ready to Review

#59 Replaced event_id to :event, project_id to :project, user_id to :user
  app/models/event.rb
  app/models/target.rb
  app/models/user.rb
Labels: Ready to Review

#50 create mailer
  Gemfile
  Gemfile.lock
  app/controllers/events_controller.rb
  app/mailers/event_mailer.rb
  app/views/event_mailer/create_event.html.haml
  app/views/event_mailer/create_event.txt.haml
  app/views/layouts/mailer.html.haml
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/active_mailer.rb
  db/seeds.rb
  spec/controllers/events_controller_spec.rb
  spec/controllers/targets_controller_spec.rb
  spec/factories/events.rb
  spec/factories/users.rb
  spec/features/user_profile_spec.rb
  spec/mailers/event_mailer_spec.rb
  spec/rails_helper.rb
  spec/support/login_helper.rb
  spec/support/phone_helper.rb
Labels: Ready to Review

#62 Bug fixed - infinity-loop
  app/javascript/components/users/UserEvents.vue
  app/javascript/src/styles/pages/_user.scss
Labels: Fixed, Ready to Review

#64 Tests for events (corrected)
  app/javascript/components/users/UserEvents.vue
  spec/features/user_profile_spec.rb
Labels: Ready to Review, Test

#65 user profile redesign
  app/javascript/components/users/UserEvents.vue
  app/javascript/components/users/UserInfo.vue
  app/javascript/components/users/show/CreateEventButton.vue
  app/javascript/packs/application.js
  app/javascript/src/styles/application.scss
  app/javascript/src/styles/pages/_show.scss
  app/javascript/src/styles/pages/_user.scss
  app/models/event.rb
  app/models/user.rb
  app/views/layouts/application.html.haml
  db/migrate/20190205101637_add_field_to_redesign.rb
  db/schema.rb
  package.json
  spec/features/user_profile_spec.rb
Labels: Ready to Review

#66 Pop-up bootstrap jquery and other
  app/controllers/events_controller.rb
  app/javascript/components/header/HeaderDropdown.vue
  app/javascript/components/users/UserEvents.vue
  app/javascript/components/users/UserInfo.vue
  app/javascript/components/users/UsersList.vue
  app/javascript/components/users/edit/EditInput.vue
  app/javascript/components/users/edit/EditSubmit.vue
  app/javascript/components/users/edit/UserEdit.vue
  app/javascript/components/users/show/CreateEventButton.vue
  app/javascript/components/users/show/CreateEventPopUp.vue
  app/javascript/packs/application.js
  app/javascript/packs/stylesheet.js
  app/javascript/src/styles/layout/_forms.scss
  app/models/event.rb
  config/locales/en.yml
  config/webpack/environment.js
  package.json
  spec/controllers/events_controller_spec.rb
  spec/models/user_spec.rb
  yarn.lock
Labels: Ready to Review

#63 test for pop up
  app/javascript/components/users/UserEvents.vue
  app/javascript/components/users/show/CreateEventPopUp.vue
  spec/factories/users.rb
  spec/features/create_edit_event_spec.rb
Labels: Ready to Review

#67 fix issues
  app/javascript/components/users/UserEvents.vue
  app/javascript/src/styles/pages/_user.scss
  app/views/layouts/application.html.haml
Labels: Ready to Review

#68 add new fields to sign up page, edit event and rewrite test
  app/controllers/application_controller.rb
  app/controllers/registrations_controller.rb
  app/controllers/users_controller.rb
  app/javascript/components/users/UserInfo.vue
  app/javascript/components/users/edit/EditSubmit.vue
  app/javascript/components/users/edit/UserEdit.vue
  app/models/user.rb
  app/views/devise/omniauth_callbacks/new.html.haml
  app/views/devise/registrations/new.html.haml
  app/views/users/edit.html.haml
  db/migrate/20190207154747_add_default_value_position.rb
  db/schema.rb
  spec/factories/users.rb
  spec/features/edit_user_spec.rb
  spec/features/sign_up_spec.rb
  spec/features/socialmedia_login_spec.rb
Labels: Ready to Review

#70 rewrite edit password page
  app/controllers/users_controller.rb
  app/javascript/components/users/edit/EditSubmit.vue
  app/javascript/components/users/edit/UserEdit.vue
  spec/controllers/users_controller_spec.rb
  spec/features/edit_user_spec.rb
Labels: Ready to Review

#71 Database Cleaner
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
  spec/support/database_cleaner.rb
Labels: Ready to Review

#69 Events Controller _Create and Update actions_
  spec/controllers/events_controller_spec.rb
Labels: Ready to Review
